spring:
    profiles.active: dev
    application.name: swagger2markup-demo
    jackson.serialization.indent_output: true

server:
    port: 9080

management:
    contextPath: /management
    add-application-context-header: false

info:
    name: ${spring.application.name}
    description: Swagger2Markup demo
    environment: ${spring.profiles.active}
    version: 1.0.0