/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest
 * Method:    showString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JniTest_showString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
