spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://localhost:8761/eureka
  #    instance-info-replication-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  server:
    eviction-interval-timer-in-ms: 50000
#    wait-time-in-ms-when-sync-empty: 5
